# Generated by Django 2.0 on 2018-08-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroCliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pessoa', models.CharField(choices=[('J', 'Pessoa Juridica'), ('F', 'Pessoa Fisica')], max_length=1, verbose_name='Tipo de Pessoa')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razao Social')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=50, verbose_name='Cnpj/Cpf')),
                ('estadual', models.CharField(max_length=50, verbose_name='Insc.Estadual')),
                ('ramo_atividade', models.CharField(max_length=50, verbose_name='Ramo de Atividade')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Endereco')),
                ('cep', models.CharField(max_length=100, verbose_name='Cep')),
                ('numero', models.CharField(max_length=5, verbose_name='Numero')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('fone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='CadastroProduto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, verbose_name='Codigo')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('embalagem', models.CharField(max_length=5, verbose_name='Embalagem')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
            ],
        ),
    ]
