# Generated by Django 2.0 on 2018-08-31 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoVenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.CadastroCliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.CadastroProduto')),
            ],
        ),
    ]
