# Generated by Django 2.0 on 2018-08-31 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_remove_cadastroproduto_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidovenda',
            name='produto',
        ),
    ]
