# Generated by Django 2.0 on 2018-08-31 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_remove_pedidovenda_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidovenda',
            old_name='cliente',
            new_name='venda',
        ),
    ]
