# Generated by Django 2.0 on 2018-08-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20180831_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidovenda',
            old_name='venda',
            new_name='cadastroproduto',
        ),
        migrations.RenameField(
            model_name='pedidovenda',
            old_name='quantidade',
            new_name='quanti',
        ),
        migrations.AddField(
            model_name='pedidovenda',
            name='produto',
            field=models.CharField(default=1, max_length=10, verbose_name='Produto'),
            preserve_default=False,
        ),
    ]
