# Generated by Django 2.0 on 2018-08-31 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20180831_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidovenda',
            name='cadastrocliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cliente.CadastroCliente'),
            preserve_default=False,
        ),
    ]
