# Generated by Django 2.0 on 2018-09-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_pedidovenda_cadastrocliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidovenda',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='pedidovenda',
            name='quanti',
        ),
        migrations.AddField(
            model_name='pedidovenda',
            name='quantidade',
            field=models.CharField(default=1, max_length=4, verbose_name='Quantidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidovenda',
            name='valor',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=5, verbose_name='Preço'),
            preserve_default=False,
        ),
    ]
