# Generated by Django 2.0 on 2018-09-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_auto_20180903_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidovenda',
            name='total',
            field=models.CharField(default=1, max_length=4, verbose_name='Total do Pedido'),
            preserve_default=False,
        ),
    ]
