# Generated by Django 2.0 on 2018-09-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_remove_pedidovenda_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidovenda',
            name='valor',
        ),
        migrations.AddField(
            model_name='pedidovenda',
            name='preco_compra',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='Preço do Produto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='quantidade',
            field=models.IntegerField(verbose_name='Qunatidade do Produto'),
        ),
    ]
