# Generated by Django 2.0 on 2018-09-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_auto_20180904_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroproduto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15, verbose_name='Preço do Produto'),
            preserve_default=False,
        ),
    ]
