# Generated by Django 2.0 on 2018-09-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_cadastroproduto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroproduto',
            name='preco',
            field=models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Preço do Produto'),
        ),
    ]
