# Generated by Django 2.0 on 2018-09-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_auto_20180921_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroproduto',
            name='preco',
            field=models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Preço do Produto'),
        ),
    ]
