# Generated by Django 2.0 on 2018-09-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0017_auto_20180921_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroproduto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço do Produto'),
        ),
    ]
